"""Add created_at to groups table

Revision ID: ffb6b634f166
Revises: 4b9113385b82
Create Date: 2025-09-07 06:18:45.793874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb6b634f166'
down_revision = '4b9113385b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'])
        batch_op.drop_column('instructor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('instructor_id')

    # ### end Alembic commands ###
